### ISSUE TITLE
Install instructions should probably reflect concurrent-1.0 required (Web Profile isn't enough)

### ISSUE THREAD

**Issue by scottkurz** [WASdev/sample.async.websockets#24]
Seems to me the app won't start without the **_concurrent-1.0**_ feature which is not in the Web Profile though [here](../blob/master/docs/Downloading-WAS-Liberty.md) it suggests the WebProfile is enough.   

For the batch BonusPayout sample,  I have a little blurb saying to use installUtility, maybe you want to follow this pattern [here](https://github.com/WASdev/sample.batch.bonuspayout/blob/master/docs/Downloading-WAS-Liberty.md) or maybe you have a better idea.  I haven't kept up with all these recent doc changes so I won't bother sending a PR.

Besides that, a typo on the Using-WDT.md page it has:**\* Gradnle Build...***

**Comment by ebullient** [comment]
I was pretty sure I had the concurrent feature in, but you're right. We'll be likely pulling in the automatic fix the install stuff we have from the 12factor sample to make sure the right features are installed..

**Comment by iainduncani** [comment]
It'd be nice if we could change the maven/gradle plugins so that they also worked with the:

installUtility install <serverName>

which installs all the features required by a given server.  This way the required features would only be defined once in the server.xml instead of being repeated again in the pom.xml and build.gradle files.

**Comment by scottkurz** [comment]
Or we could just say to grab the full EE 7 download

**Comment by ebullient** [comment]
Our maven gradle tools will pull the needed featurea if you use them. I would rather not encourage full

---

Erin Schnabel schnabel@us.ibm.com
WebSphere Application Server - Development Lead for the Liberty runtime
845.435.5648 / 8.295.5648
i ♥ liberty

**Comment by ebullient** [comment]
Meaning, we did what Iain suggested, IIRC

---

Erin Schnabel schnabel@us.ibm.com
WebSphere Application Server - Development Lead for the Liberty runtime
845.435.5648 / 8.295.5648
i ♥ liberty

**Comment by scottkurz** [comment]
That's true, but that only helps if you use the -DlibertyRoot to point to Liberty, which the command line doc suggests you do that if you want to run the tests.   If you just want to build the app and then go point the browser to it, or if you just don't read carefully thinking "mvn install" should just work, you're still not working out of the gate.

This all isn't that hard to figure out, but there are so many install options in Liberty it seems worth spelling it out.
